apiVersion: apps/v1
kind: Deployment
metadata:
  name: mctechpayments
#  namespace: mctech-payments-space
  labels:
    app: mctechpayments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mctechpayments
  template:
    metadata:
      labels:
        app: mctechpayments
    spec:
      containers:
        - name: mctechpayments-container
          image: ghcr.io/grupo-68-fiap/mctech/payment:latest # NOSONAR
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: mctechpayments-secret
                  key: CONNECTION_STRING
            - name: OPENID_AUTHORITY
              valueFrom:
                secretKeyRef:
                  name: cognito-secrets
                  key: OPENID_AUTHORITY
            - name: OPENID_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: cognito-secrets
                  key: OPENID_AUDIENCE
          envFrom:
            - configMapRef:
                name: mctechpayments-configmap        
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /swagger
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /swagger
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 30
          resources:
            requests:
              memory: 64Mi
              cpu: 5m
              ephemeral-storage: "1Gi"
            limits:
              memory: 256Mi
              cpu: 200m
              ephemeral-storage: "2Gi"
      automountServiceAccountToken: false
