apiVersion: v1 # Service da API do tipo LoadBalancer
kind: Service
metadata:
  labels:
      app: mctechpayments-svc
  name: mctechpayments-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: mctechpayments
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
